### ISSUE TITLE
[Feature]: 상세 페이지

### ISSUE THREAD

**Issue by InYoung05** [pknu-wap/Y-NOT-Project#20]
## 💫 설명
- PR 설명
 상세 페이지 틀 할 수 있을 때까지 짜기 + 가로 스크롤 기능 구현 + 이미지 파일 오류 조정
## Todo

- [ ]  todo 1 상세 페이지 스크롤 기능과 이미지 첨가 기능 구현
- [ ]  todo 2 이미지 가로 스크롤과 더미 데이터 활용해서 책 데이터 기입하기
- [x]  todo 3 네비게이션 바의 창 전환 기능 구현
## 기타

- 기타사항 작성
