### ISSUE TITLE
[Feature]: 각종오류해결

### ISSUE THREAD

**Issue by phy-ju** [pknu-wap/Y-NOT-Project#21]
## 💫 설명
- 합친 후 발생한 오류해결

## Todo

- [ ]  사진 파일명 수정
- [ ]  navigator -> get 으로 수정
- [ ] main 파일 정리
