### ISSUE TITLE
[Feature]: 채팅

### ISSUE THREAD

**Issue by phy-ju** [pknu-wap/Y-NOT-Project#25]
## 💫 설명
- 사용자들끼리 이야기할 채팅창입니다

## Todo

- [x]  파이어베이스와 플러터 연동
- [ ]  입력하면 DB 안에 넣기
- [x]  채팅 UI제작
- [x] 실시간으로 사용할 수 있게

## 기타

- 백엔드를 동시에 혼자 만져서 속도 느릴 수도 있음
