### ISSUE TITLE
[Feature]: 마이페이지

### ISSUE THREAD

**Issue by InYoung05** [pknu-wap/Y-NOT-Project#37]
## 💫 설명
- PR 설명

## Todo

- [x]  네비게이터로 창 전환 기능 구현
- [x]  안 만들어진 창들은 임의로 지정하고 수정
- [x]  프로필 아이콘 수정 기능 구현
- [ ]  닉네임 사용자 정보랑 연동해서 가져오기
- [x]  하단바 오류 수정 -> 현주 하단바 가져오기
- [ ]  이미지 업로드 기능 오류 수정

## 기타

- 기타사항 작성
