### ISSUE TITLE
[Feature]: 채팅기능2

### ISSUE THREAD

**Issue by phy-ju** [pknu-wap/Y-NOT-Project#40]
## 💫 설명
- 채팅 재개발 및 디자인 변경

## Todo

- [x]  기존 파일 지우고 고치기
- [x]  관련 자료 더 찾아보기
- [ ] chatview를 chat으로 바꾸기
- [x] db연동 및 메시지 저장 확인
- [ ] 목록창 각각 메시지 방 만들기
- [x] 파이어베이스에 user정보 추가
- [ ] 

## 기타

-이미 어느정도 완성되어 있으나 더 나은 경우가 보여 늦기 전에 바꿀려고함
