### ISSUE TITLE
[Feature]: 메인페이지 개발

### ISSUE THREAD

**Issue by phy-ju** [pknu-wap/Y-NOT-Project#6]
## 💫 설명
로그인 후 보이는 메인 페이지 개발

## Todo

- [x]  사진 여백 키우기
- [x]  알림,저장 페이지 연결
- [ ] 사용자명 불러오기
- [x] 밑에 계속 연결해서,,

## 기타

- 중간고사 이후 할 예정,,
