### ISSUE TITLE
[Feature]: 상세 페이지

### ISSUE THREAD

**Issue by InYoung05** [pknu-wap/Y-NOT-Project#60]
## 💫 설명
- PR 설명
 풀 요청이 한번에 너무 많이 받아져서 충돌 다발 -> 브랜치 새로 생성 후 복붙
## Todo

- [x]  상세 페이지 스크롤 기능과 이미지 표시 기능 구현
- [ ] 이미지 가로 스크롤과 더미 데이터 활용해서 책 데이터 기입하기
- [x]  네비게이션 바의 창 전환 기능 구현
## 기타

- 기타사항 작성
