### ISSUE TITLE
[Feature]: Connect data

### ISSUE THREAD

**Issue by phy-ju** [pknu-wap/Y-NOT-Project#74]
## 💫 설명
- 플러터와 파이어베이스가 서로 데이터를 주고 받을 수 있도록

## Todo

- [x]  플러터가 데이터 주기
- [x]  파베로부터 데이터 받기
- [x] 검색창 기능 불러오기 완성
- [x] 메인페이지 각 사진마다 넣기
- [x] 저장 목록 완성
- [ ] 

## 기타

- 일단 채팅은 우선순위 밀려남,,
