### ISSUE TITLE
[Feature]: 회원 가입

### ISSUE THREAD

**Issue by InYoung05** [pknu-wap/Y-NOT-Project#8]
## 💫 설명
- PR 설명
회원 가입 창 구현 + 창 전환 
## Todo

- [x] 회원가입 기능별로 폴더 나누기
- [x] 버튼 별로 창 전환 기능 구현
- [x] 이메일 유효성 검사 기능 추가
- [x] 비밀번호 조건 추가
- [x] 닉네임 설정 중복 검사 기능 추가
- [x] 부경대 학교 계정으로만 가입 가능하게 이메일 유효성 코드 수정

## 기타

- 기타사항 작성
